apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: business-transaction-anti-fraud-v1-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: business-transaction-anti-fraud-v1
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 900  # target_average_cpu (representa el % de uso de CPU por pod)
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 350  # target_average_memory (representa el % de uso de memoria por pod)